spring.main.banner-mode=off
spring.main.web-application-type=none
spring.ai.mcp.server.name=news-api-mcp
spring.ai.mcp.server.version=1.0.0
spring.ai.mcp.server.stdio=true
logging.config=classpath:logback-spring.xml

news.api.key=c5fedb86dff94a569e2bb1c73f44b9ef